services:
  # --- FRONTEND ---
  frontend-angular:
    build:
      context: ../tfg_frontend
      dockerfile: Dockerfile
    container_name: frontend-angular
    ports:
      - "8080:8080"
    depends_on:
      - backend-fastapi

  # --- BACKEND ---
  backend-fastapi:
    build:
      context: ../tfg_backend
      dockerfile: Dockerfile
    container_name: backend-fastapi
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_SERVER: db-postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${DB_NAME}
      REDIS_HOST: cache-redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      FILESYSTEM_URL: http://filesystem-minio:9000
      FILESYSTEM_ID_KEY: ${MINIO_ROOT_USER}
      FILESYSTEM_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      FORCE_PATH_STYLE: "true"
      REGION_NAME: us-east-1
      BUCKET_NAME: ${BUCKET_NAME}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      db-postgres:
        condition: service_healthy
      cache-redis:
        condition: service_healthy
      filesystem-minio:
        condition: service_healthy

  # --- WORKER ---
  worker-rq:
    build:
      context: ../tfg_worker
      dockerfile: Dockerfile
    container_name: worker-rq
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_SERVER: db-postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${DB_NAME}
      REDIS_HOST: cache-redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      FILESYSTEM_URL: http://filesystem-minio:9000
      FILESYSTEM_ID_KEY: ${MINIO_ROOT_USER}
      FILESYSTEM_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      FORCE_PATH_STYLE: "true"
      REGION_NAME: us-east-1
      BUCKET_NAME: ${BUCKET_NAME}
      DW_MODEL_PATH: ${DW_MODEL_PATH}
      DEM_MODEL_PATH: ${DEM_MODEL_PATH}
      CW_MODEL_PATH: ${CW_MODEL_PATH}
    depends_on:
      db-postgres:
        condition: service_healthy
      cache-redis:
        condition: service_healthy
      filesystem-minio:
        condition: service_healthy

  # --- DATA CONTAINERS ---
  db-postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  cache-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  filesystem-minio:
    image: quay.io/minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: minio server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:
  redis_data:
  minio_data:
